name: sharing
description: Schedule sharing feature module
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  supabase_flutter: ^2.0.0
  dartz: ^0.10.1
  qr_flutter: ^4.1.0
  share_plus: ^10.0.0
  app_links: ^6.4.1
  google_fonts: ^6.2.1
  json_annotation: ^4.9.0

  common:
    path: ../common
  course:
    path: ../course
  schedule:
    path: ../schedule
  supply:
    path: ../supply

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.0
  riverpod_generator: ^2.6.5
  json_serializable: ^6.9.5

flutter:
